name: Python CI

on:
  push:
    branches:
      - main

jobs:
  run-demo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Run demo.py
      run: python demo.py
